# Generated by Django 4.2 on 2023-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_members_firstname_remove_members_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='content',
        ),
        migrations.RemoveField(
            model_name='members',
            name='tomtat',
        ),
        migrations.RemoveField(
            model_name='members',
            name='type',
        ),
        migrations.AddField(
            model_name='members',
            name='CK',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='GK',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='GOAL',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='hs11',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='hs12',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='hs13',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='hs14',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
