# Generated by Django 4.1.7 on 2023-04-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_remove_members_content_remove_members_tomtat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members", name="CK", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="members", name="GK", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="members", name="GOAL", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="members", name="hs11", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="members", name="hs12", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="members", name="hs13", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="members", name="hs14", field=models.CharField(max_length=255),
        ),
    ]
